---
- name: Terraform Backend configuration file
  hosts: localhost
  gather_facts: false

  tasks:
    - name: Create a simple terraform project
      cloud.terraform.terraform:
        force_init: true
        state: present
        project_path: '{{ tf_path }}'
        backend_config_files: "{{ lookup('env', 'TF_BACKEND_CONFIG_FILE') }}"
