- name: Terraform apply
  hosts: localhost
  gather_facts: false
  vars:
    project_dir: /tmp/tf
  tasks:
    - name: Copy terraform files to project dir
      ansible.builtin.copy:
        src: tf
        dest: /tmp

    - name: Get stashed plan
      cloud.terraform.plan_stash:
        state: load
        path: "{{ project_dir }}/tfplan"

    - name: Apply plan
      cloud.terraform.terraform:
        force_init: true
        project_path: '{{ project_dir }}'
        state: present
        plan_file: "{{ project_dir }}/tfplan"
      register: apply_result

    - name: Log stdout for review
      ansible.builtin.debug:
        msg: "{{ apply_result.stdout_lines }}"
