---
- name: Terraform plan
  hosts: localhost
  gather_facts: false
  vars:
    project_dir: /tmp/tf
  tasks:
    - name: Copy terraform files to project dir
      ansible.builtin.copy:
        src: tf
        dest: /tmp

    - name: Generate plan
      cloud.terraform.terraform:
        force_init: true
        project_path: "{{ project_dir }}"
        state: present
        plan_file: "{{ project_dir }}/tfplan"
      check_mode: true
      register: plan_result

    - name: Stash plan for later use
      cloud.terraform.plan_stash:
        path: "{{ project_dir }}/tfplan"
        per_host: true

    - name: Log diff for review
      ansible.builtin.debug:
        msg: "{{ plan_result }}"
