---
- name: Terraform plan
  hosts: localhost
  gather_facts: false
  vars:
    project_dir: /tmp/tf
  tasks:
    - name: Copy terraform files to project dir
      ansible.builtin.copy:
        src: tf
        dest: /tmp

    - name: Generate plan
      cloud.terraform.terraform:
        force_init: true
        project_path: "{{ project_dir }}"
        state: present
        plan_file: "./tfplan"
      check_mode: true
      register: plan_result

    - name: Get base64-encoded plan file contents
      ansible.builtin.slurp:
        src: "{{ project_dir }}/tfplan"
      register: slurp_result

    - name: Add encoded plan contents to stats
      ansible.builtin.set_stats:
        data:
          tfplan: "{{ slurp_result.content }}"

    - name: Log diff for review
      ansible.builtin.debug:
        msg: "{{ plan_result.diff }}"
